[build]
builder = "nixpacks"

[build.args]
NIXPACKS_INSTALL_CMD = "composer install --no-dev --optimize-autoloader && npm install"
NIXPACKS_BUILD_CMD = "npm run build"

[deploy]
startCommand = "sh deployment/start.sh"
restartPolicyType = "on_failure"